databases:
  - name: botthaghosa
    databaseName: botthaghosa
    user: botthaghosa
    plan: starter

services:
  - type: redis
    name: cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: noeviction

  - type: worker
    name: sidekiq-worker
    runtime: ruby
    buildCommand: 'bundle install'
    startCommand: 'bundle exec sidekiq'
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: botthaghosa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: cron
    name: scheduled_messages
    env: ruby
    schedule: '0 8 * * *'
    buildCommand: 'bundle install'
    startCommand: 'bundle exec rake scheduled_messages:attempt'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botthaghosa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString

  - type: cron
    name: credentials_check
    env: ruby
    schedule: '0 0 * * *'
    buildCommand: 'bundle install'
    startCommand: 'bundle exec rake credentials:check'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botthaghosa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString

  - type: web
    name: botthaghosa
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botthaghosa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
