databases:
  - name: botthaghosa
    databaseName: botthaghosa
    user: botthaghosa
    plan: starter

services:
  - type: redis
    name: cache
    ipAllowList: []
    plan: starter
    maxmemoryPolicy: allkeys-lfu
  - type: web
    name: botthaghosa
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: botthaghosa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: REDIS_URL
        fromService:
          type: redis
          name: cache
          property: connectionString
